### ISSUE TITLE
This module requires policycoreutils-python

### ISSUE THREAD

**Issue by ivn86** [bngsudheer/ansible-role-redmine#23]
https://github.com/bngsudheer/ansible-role-redmine/blob/ee631dcbbc9b3b74f5d4c0bbe6463ee9547c0f9c/tasks/main.yml#L73

FAILED! => {"changed": false, "msg": "This module requires policycoreutils-python"}

**Comment by bngsudheer** [comment]
The role depends on https://galaxy.ansible.com/bngsudheer/centos_base/. You have to use centos_base or another means to install policycoreutils-python packages. For simplicity you can have it your pre_tasks.

**Comment by ivn86** [comment]
Му playbook is:

```
- hosts: redmine
  remote_user: root
  vars:
  - centos_base_enable_epel: true
  - centos_base_basic_packages: true
  - redmine_sql_username: redmine
  - redmine_sql_password: password
  - redmine_sql_database_name: redmine
  - remmine_sql_database_host: localhost
  - redmine_nginx_bind_ip: 192.168.23.245
  - redmine_configure_selinux: yes
  - redmine_plugins:
    - name: scrum
      base_name: scrum
      url: https://redmine.ociotec.com/attachments/download/481/scrum-v0.18.1.tar.gz
      create_base_directory: false
  roles:
    - bngsudheer.centos_base
    - bngsudheer.redmine
```
