### ISSUE TITLE
Unicorn will not start

### ISSUE THREAD

**Issue by jkugler** [bngsudheer/ansible-role-redmine#25]
I am using this role on a CentOS 7.6 system. Everything seems to be configured correctly. The database is migrated (from a rather old version, yay!) but unicorn will not start. The stderr log has this over and over:
```
I, [2019-03-14T14:40:13.322666 #15687]  INFO -- : Refreshing Gem list
/home/redmine/.gem/ruby/gems/unicorn-5.5.0/lib/unicorn.rb:49:in `block in builder': wrong number of arguments (0 for 2) (ArgumentError)
        from /home/redmine/.gem/ruby/gems/unicorn-5.5.0/bin/unicorn_rails:139:in `call'
        from /home/redmine/.gem/ruby/gems/unicorn-5.5.0/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/.gem/ruby/gems/unicorn-5.5.0/lib/unicorn/http_server.rb:794:in `call'
        from /home/redmine/.gem/ruby/gems/unicorn-5.5.0/lib/unicorn/http_server.rb:794:in `build_app!'
        from /home/redmine/.gem/ruby/gems/unicorn-5.5.0/lib/unicorn/http_server.rb:141:in `start'
        from /home/redmine/.gem/ruby/gems/unicorn-5.5.0/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/bin/unicorn_rails:23:in `load'
        from /home/redmine/bin/unicorn_rails:23:in `<main>'
```
This is in my meta/galaxy_install_info
```
{install_date: 'Sat Mar  9 22:41:55 2019', version: v2.0.2}
```
These are the settings I'm using for the install:
```
  vars:
    redmine_sql_driver: postgresql
    redmine_sql_username: redmine
    redmine_sql_password: "{{ postgresql_password }}"
    redmine_sql_database_name: redmine
    redmine_sql_database_host: 192.168.122.5
    centos_base_selinux_packages: false
    redmine_domain_name: projects.example.com
    redmine_configure_nginx: true
    redmine_nginx_config_template: tls
    redmine_ssl_certificate_path: /etc/ssl/certs/star_example.com.pem
    redmine_ssl_certificate_key_path: /etc/ssl/private/star_example.com.key
    redmine_configure_firewalld: false
    redmine_enable_smtp_email: true
    redmine_smtp_settings_domain: projects.example.com
```
Any help would be great!
```
# rpm -qa|grep ruby
rubygem-io-console-0.4.2-34.el7_6.x86_64
rubygem-bigdecimal-1.2.0-34.el7_6.x86_64
rubygem-json-1.7.7-34.el7_6.x86_64
rubygem-psych-2.0.0-34.el7_6.x86_64
ruby-2.0.0.648-34.el7_6.x86_64
rubygems-2.0.14.1-34.el7_6.noarch
ruby-devel-2.0.0.648-34.el7_6.x86_64
ruby-libs-2.0.0.648-34.el7_6.x86_64
ruby-irb-2.0.0.648-34.el7_6.noarch
rubygem-rdoc-4.0.0-34.el7_6.noarch
# rpm -qa|grep nginx
nginx-filesystem-1.12.2-2.el7.noarch
nginx-mod-http-geoip-1.12.2-2.el7.x86_64
nginx-1.12.2-2.el7.x86_64
nginx-mod-http-perl-1.12.2-2.el7.x86_64
nginx-mod-mail-1.12.2-2.el7.x86_64
nginx-mod-stream-1.12.2-2.el7.x86_64
nginx-mod-http-image-filter-1.12.2-2.el7.x86_64
nginx-mod-http-xslt-filter-1.12.2-2.el7.x86_64
nginx-all-modules-1.12.2-2.el7.noarch
```
Any other output you'd like, let me know!
